# Generated by Django 5.0.4 on 2024-07-08 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dialog", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="answer",
            old_name="content",
            new_name="answer_text",
        ),
        migrations.AlterField(
            model_name="answer",
            name="create_date",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="question",
            name="pub_date",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
